language: python
python: 
  - "3.6.6"
env:
  - DJANGO=2.0 DB=postgres
install:
  - pip install -r requirements.txt
before_script:
  - cd decide
  - cp local_settings.travis.py local_settings.py
  - psql -c "create user decide with password 'decide'"
  - psql -c "create database decide owner decide"
  - python manage.py makemigrations
  - python manage.py migrate
script:
  - ./manage.py test mixnet
sudo: required
services:
  - postgresql
addons:
  postgresql: "9.6"
  sonarcloud:
    organization: "pablotabares-github"
global:
  - PGPORT=5432
notifications:
  email: false
